// Generated by gencpp from file cpr_robot/RobotCommandResponse.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_ROBOTCOMMANDRESPONSE_H
#define CPR_ROBOT_MESSAGE_ROBOTCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpr_robot
{
template <class ContainerAllocator>
struct RobotCommandResponse_
{
  typedef RobotCommandResponse_<ContainerAllocator> Type;

  RobotCommandResponse_()
    {
    }
  RobotCommandResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotCommandResponse_

typedef ::cpr_robot::RobotCommandResponse_<std::allocator<void> > RobotCommandResponse;

typedef boost::shared_ptr< ::cpr_robot::RobotCommandResponse > RobotCommandResponsePtr;
typedef boost::shared_ptr< ::cpr_robot::RobotCommandResponse const> RobotCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpr_robot::RobotCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cpr_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cpr_robot::RobotCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpr_robot/RobotCommandResponse";
  }

  static const char* value(const ::cpr_robot::RobotCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::cpr_robot::RobotCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpr_robot::RobotCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cpr_robot::RobotCommandResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_ROBOTCOMMANDRESPONSE_H
