(cl:defpackage cpr_robot-srv
  (:use )
  (:export
   "GETJOINTINFO"
   "<GETJOINTINFO-REQUEST>"
   "GETJOINTINFO-REQUEST"
   "<GETJOINTINFO-RESPONSE>"
   "GETJOINTINFO-RESPONSE"
   "GETROBOTINFO"
   "<GETROBOTINFO-REQUEST>"
   "GETROBOTINFO-REQUEST"
   "<GETROBOTINFO-RESPONSE>"
   "GETROBOTINFO-RESPONSE"
   "ROBOTCOMMAND"
   "<ROBOTCOMMAND-REQUEST>"
   "ROBOTCOMMAND-REQUEST"
   "<ROBOTCOMMAND-RESPONSE>"
   "ROBOTCOMMAND-RESPONSE"
  ))

