// Generated by gencpp from file cpr_robot/RobotCommandRequest.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_ROBOTCOMMANDREQUEST_H
#define CPR_ROBOT_MESSAGE_ROBOTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpr_robot
{
template <class ContainerAllocator>
struct RobotCommandRequest_
{
  typedef RobotCommandRequest_<ContainerAllocator> Type;

  RobotCommandRequest_()
    : Sender()
    , CommandId(0)
    , PayloadFloat(0.0)
    , PayloadInt(0)  {
    }
  RobotCommandRequest_(const ContainerAllocator& _alloc)
    : Sender(_alloc)
    , CommandId(0)
    , PayloadFloat(0.0)
    , PayloadInt(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Sender_type;
  _Sender_type Sender;

   typedef uint32_t _CommandId_type;
  _CommandId_type CommandId;

   typedef double _PayloadFloat_type;
  _PayloadFloat_type PayloadFloat;

   typedef int64_t _PayloadInt_type;
  _PayloadInt_type PayloadInt;





  typedef boost::shared_ptr< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotCommandRequest_

typedef ::cpr_robot::RobotCommandRequest_<std::allocator<void> > RobotCommandRequest;

typedef boost::shared_ptr< ::cpr_robot::RobotCommandRequest > RobotCommandRequestPtr;
typedef boost::shared_ptr< ::cpr_robot::RobotCommandRequest const> RobotCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpr_robot::RobotCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpr_robot::RobotCommandRequest_<ContainerAllocator1> & lhs, const ::cpr_robot::RobotCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Sender == rhs.Sender &&
    lhs.CommandId == rhs.CommandId &&
    lhs.PayloadFloat == rhs.PayloadFloat &&
    lhs.PayloadInt == rhs.PayloadInt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpr_robot::RobotCommandRequest_<ContainerAllocator1> & lhs, const ::cpr_robot::RobotCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpr_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4ae46840bac87549d3c8ef9dbcd298d";
  }

  static const char* value(const ::cpr_robot::RobotCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4ae46840bac8754ULL;
  static const uint64_t static_value2 = 0x9d3c8ef9dbcd298dULL;
};

template<class ContainerAllocator>
struct DataType< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpr_robot/RobotCommandRequest";
  }

  static const char* value(const ::cpr_robot::RobotCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Sender\n"
"uint32 CommandId\n"
"float64 PayloadFloat\n"
"int64 PayloadInt\n"
;
  }

  static const char* value(const ::cpr_robot::RobotCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sender);
      stream.next(m.CommandId);
      stream.next(m.PayloadFloat);
      stream.next(m.PayloadInt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpr_robot::RobotCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpr_robot::RobotCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "Sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Sender);
    s << indent << "CommandId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.CommandId);
    s << indent << "PayloadFloat: ";
    Printer<double>::stream(s, indent + "  ", v.PayloadFloat);
    s << indent << "PayloadInt: ";
    Printer<int64_t>::stream(s, indent + "  ", v.PayloadInt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_ROBOTCOMMANDREQUEST_H
