// Generated by gencpp from file cpr_robot/GetJointInfo.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_GETJOINTINFO_H
#define CPR_ROBOT_MESSAGE_GETJOINTINFO_H

#include <ros/service_traits.h>


#include <cpr_robot/GetJointInfoRequest.h>
#include <cpr_robot/GetJointInfoResponse.h>


namespace cpr_robot
{

struct GetJointInfo
{

typedef GetJointInfoRequest Request;
typedef GetJointInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointInfo
} // namespace cpr_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpr_robot::GetJointInfo > {
  static const char* value()
  {
    return "06bfa666ccf7ae403dfc3460222a104e";
  }

  static const char* value(const ::cpr_robot::GetJointInfo&) { return value(); }
};

template<>
struct DataType< ::cpr_robot::GetJointInfo > {
  static const char* value()
  {
    return "cpr_robot/GetJointInfo";
  }

  static const char* value(const ::cpr_robot::GetJointInfo&) { return value(); }
};


// service_traits::MD5Sum< ::cpr_robot::GetJointInfoRequest> should match
// service_traits::MD5Sum< ::cpr_robot::GetJointInfo >
template<>
struct MD5Sum< ::cpr_robot::GetJointInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::GetJointInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetJointInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::GetJointInfoRequest> should match
// service_traits::DataType< ::cpr_robot::GetJointInfo >
template<>
struct DataType< ::cpr_robot::GetJointInfoRequest>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::GetJointInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetJointInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpr_robot::GetJointInfoResponse> should match
// service_traits::MD5Sum< ::cpr_robot::GetJointInfo >
template<>
struct MD5Sum< ::cpr_robot::GetJointInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::GetJointInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetJointInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::GetJointInfoResponse> should match
// service_traits::DataType< ::cpr_robot::GetJointInfo >
template<>
struct DataType< ::cpr_robot::GetJointInfoResponse>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::GetJointInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetJointInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_GETJOINTINFO_H
