// Generated by gencpp from file cpr_robot/GetRobotInfoRequest.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_GETROBOTINFOREQUEST_H
#define CPR_ROBOT_MESSAGE_GETROBOTINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpr_robot
{
template <class ContainerAllocator>
struct GetRobotInfoRequest_
{
  typedef GetRobotInfoRequest_<ContainerAllocator> Type;

  GetRobotInfoRequest_()
    : Sender()  {
    }
  GetRobotInfoRequest_(const ContainerAllocator& _alloc)
    : Sender(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Sender_type;
  _Sender_type Sender;





  typedef boost::shared_ptr< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotInfoRequest_

typedef ::cpr_robot::GetRobotInfoRequest_<std::allocator<void> > GetRobotInfoRequest;

typedef boost::shared_ptr< ::cpr_robot::GetRobotInfoRequest > GetRobotInfoRequestPtr;
typedef boost::shared_ptr< ::cpr_robot::GetRobotInfoRequest const> GetRobotInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator1> & lhs, const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Sender == rhs.Sender;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator1> & lhs, const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpr_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf661c295c93387e71dbd70441d1cc44";
  }

  static const char* value(const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf661c295c93387eULL;
  static const uint64_t static_value2 = 0x71dbd70441d1cc44ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpr_robot/GetRobotInfoRequest";
  }

  static const char* value(const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Sender\n"
;
  }

  static const char* value(const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sender);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpr_robot::GetRobotInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "Sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Sender);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_GETROBOTINFOREQUEST_H
