// Generated by gencpp from file cpr_robot/GetRobotInfo.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_GETROBOTINFO_H
#define CPR_ROBOT_MESSAGE_GETROBOTINFO_H

#include <ros/service_traits.h>


#include <cpr_robot/GetRobotInfoRequest.h>
#include <cpr_robot/GetRobotInfoResponse.h>


namespace cpr_robot
{

struct GetRobotInfo
{

typedef GetRobotInfoRequest Request;
typedef GetRobotInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotInfo
} // namespace cpr_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpr_robot::GetRobotInfo > {
  static const char* value()
  {
    return "e575ccf5296d82bf7ce2a23f1cc16a78";
  }

  static const char* value(const ::cpr_robot::GetRobotInfo&) { return value(); }
};

template<>
struct DataType< ::cpr_robot::GetRobotInfo > {
  static const char* value()
  {
    return "cpr_robot/GetRobotInfo";
  }

  static const char* value(const ::cpr_robot::GetRobotInfo&) { return value(); }
};


// service_traits::MD5Sum< ::cpr_robot::GetRobotInfoRequest> should match
// service_traits::MD5Sum< ::cpr_robot::GetRobotInfo >
template<>
struct MD5Sum< ::cpr_robot::GetRobotInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::GetRobotInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetRobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::GetRobotInfoRequest> should match
// service_traits::DataType< ::cpr_robot::GetRobotInfo >
template<>
struct DataType< ::cpr_robot::GetRobotInfoRequest>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::GetRobotInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetRobotInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpr_robot::GetRobotInfoResponse> should match
// service_traits::MD5Sum< ::cpr_robot::GetRobotInfo >
template<>
struct MD5Sum< ::cpr_robot::GetRobotInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::GetRobotInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetRobotInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::GetRobotInfoResponse> should match
// service_traits::DataType< ::cpr_robot::GetRobotInfo >
template<>
struct DataType< ::cpr_robot::GetRobotInfoResponse>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::GetRobotInfo >::value();
  }
  static const char* value(const ::cpr_robot::GetRobotInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_GETROBOTINFO_H
