// Generated by gencpp from file cpr_robot/RobotCommand.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_ROBOTCOMMAND_H
#define CPR_ROBOT_MESSAGE_ROBOTCOMMAND_H

#include <ros/service_traits.h>


#include <cpr_robot/RobotCommandRequest.h>
#include <cpr_robot/RobotCommandResponse.h>


namespace cpr_robot
{

struct RobotCommand
{

typedef RobotCommandRequest Request;
typedef RobotCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotCommand
} // namespace cpr_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpr_robot::RobotCommand > {
  static const char* value()
  {
    return "b4ae46840bac87549d3c8ef9dbcd298d";
  }

  static const char* value(const ::cpr_robot::RobotCommand&) { return value(); }
};

template<>
struct DataType< ::cpr_robot::RobotCommand > {
  static const char* value()
  {
    return "cpr_robot/RobotCommand";
  }

  static const char* value(const ::cpr_robot::RobotCommand&) { return value(); }
};


// service_traits::MD5Sum< ::cpr_robot::RobotCommandRequest> should match
// service_traits::MD5Sum< ::cpr_robot::RobotCommand >
template<>
struct MD5Sum< ::cpr_robot::RobotCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::RobotCommand >::value();
  }
  static const char* value(const ::cpr_robot::RobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::RobotCommandRequest> should match
// service_traits::DataType< ::cpr_robot::RobotCommand >
template<>
struct DataType< ::cpr_robot::RobotCommandRequest>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::RobotCommand >::value();
  }
  static const char* value(const ::cpr_robot::RobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpr_robot::RobotCommandResponse> should match
// service_traits::MD5Sum< ::cpr_robot::RobotCommand >
template<>
struct MD5Sum< ::cpr_robot::RobotCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpr_robot::RobotCommand >::value();
  }
  static const char* value(const ::cpr_robot::RobotCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpr_robot::RobotCommandResponse> should match
// service_traits::DataType< ::cpr_robot::RobotCommand >
template<>
struct DataType< ::cpr_robot::RobotCommandResponse>
{
  static const char* value()
  {
    return DataType< ::cpr_robot::RobotCommand >::value();
  }
  static const char* value(const ::cpr_robot::RobotCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_ROBOTCOMMAND_H
