// Generated by gencpp from file cpr_robot/RobotState.msg
// DO NOT EDIT!


#ifndef CPR_ROBOT_MESSAGE_ROBOTSTATE_H
#define CPR_ROBOT_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cpr_robot
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : Header()
    , Override(0.0)
    , StatusFlags(0)  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , Override(0.0)
    , StatusFlags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef double _Override_type;
  _Override_type Override;

   typedef uint32_t _StatusFlags_type;
  _StatusFlags_type StatusFlags;





  typedef boost::shared_ptr< ::cpr_robot::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpr_robot::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::cpr_robot::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::cpr_robot::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::cpr_robot::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpr_robot::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpr_robot::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cpr_robot::RobotState_<ContainerAllocator1> & lhs, const ::cpr_robot::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.Override == rhs.Override &&
    lhs.StatusFlags == rhs.StatusFlags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cpr_robot::RobotState_<ContainerAllocator1> & lhs, const ::cpr_robot::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cpr_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpr_robot::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpr_robot::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpr_robot::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpr_robot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f1e4c5a63d074be8d818e2683b635ac";
  }

  static const char* value(const ::cpr_robot::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f1e4c5a63d074beULL;
  static const uint64_t static_value2 = 0x8d818e2683b635acULL;
};

template<class ContainerAllocator>
struct DataType< ::cpr_robot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpr_robot/RobotState";
  }

  static const char* value(const ::cpr_robot::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpr_robot::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header Header\n"
"float64 Override\n"
"uint32 StatusFlags\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cpr_robot::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpr_robot::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.Override);
      stream.next(m.StatusFlags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpr_robot::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpr_robot::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "Override: ";
    Printer<double>::stream(s, indent + "  ", v.Override);
    s << indent << "StatusFlags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.StatusFlags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPR_ROBOT_MESSAGE_ROBOTSTATE_H
